### ISSUE TITLE
Can't parse a trio file when a string is begining with a number

### ISSUE THREAD

**Issue by tuscaonline** [engie-group/shaystack#10]
**Describe the bug**
in trio mode when a dis is begining with a number the parsing fail

**To Reproduce**
trio = """---
id: @muz.A.r1
dis: 1er etage bâtiment A
space: M
floor: M
floorNum: 2.0
siteRef: @muz"""
g=shaystack.parse(trio, mode= shaystack.MODE_TRIO)

**Expected behavior**
I expect a string parsing

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Amine-OMRI** [comment]
Hello @tuscaonline , it works fine, just quote the string value like below:
```
trio = shaystack.parse(
        """---
        id: @muz.A.r1
        dis: "1er etage bâtiment A"
        space: M
        floor: M
        floorNum: 2.0
        siteRef: @muz
        """
        , mode=shaystack.MODE_TRIO)
    print(shaystack.dump(trio))
```
For more details about TRIO parsing and foramting here is the [documentation](https://www.project-haystack.org/doc/docHaystack/Trio)
Thanks!

**Comment by tuscaonline** [comment]
Yes, but your dumper don't quote the string.
