### ISSUE TITLE
shaystack is not compatible with Python 3.10

### ISSUE THREAD

**Issue by gr-hayduk** [engie-group/shaystack#6]
After trying to start shystack under Python 3.10, it reports only a message that 
`"To start shift-4-haystack, use 'pip install "shaystack[flask]"' or 'pip install "shaystack[flask,graphql]"' and set 'HAYSTACK_PROVIDER' variable"`
despite the variable is defined (and HAYSTACK_DB also is defined). 
After modification of site-packages/app/main.py to include text of the exception (print(str(ex)), I have encountered several errors from flask and other modules and finally from Python base module:
`"cannot import MutableSequence from collections"`
After modification of shystack/grid.py to import MutableSequence from collections.abc instead of just collections, I got uncaught exception (python simply crashes after few seconds).

1. Install Python 3.10.4 (x64), shaystack, flask==2.0.3 (current one has issues with shaystack), graphql
2. Define HAYSTACK_PROVIDER and HAYSTACK_DB
3. start shystack
4. See error in system log (event viewer in Windows)

**Expected behavior**
Be able to start shaystack and use its web interface.

**Desktop :**
 - OS: Windows 10 x64

Please help how to launch shaystack.

**Comment by tuscaonline** [comment]
I have the same problem in unbuntu
ImportError                               Traceback (most recent call last)
/home/tusca/haystack/haystack.ipynb Cellule 4 in <cell line: 1>()
----> [1](vscode-notebook-cell:/home/tusca/haystack/haystack.ipynb#ch0000003?line=0) import shaystack
      [2](vscode-notebook-cell:/home/tusca/haystack/haystack.ipynb#ch0000003?line=1) import datetime

File ~/haystack/venv/lib/python3.10/site-packages/shaystack/__init__.py:25, in <module>
      8 """
      9 Implementation of Haystack project https://www.project-haystack.org/
     10 Propose API :
   (...)
     21 - and expose the data via Flask or AWS Lambda
     22 """
     23 from .datatypes import Quantity, Coordinate, Uri, Bin, MARKER, NA, \
     24     REMOVE, Ref, XStr
---> 25 from .dumper import dump, dump_scalar
     26 from .grid import Grid
     27 from .grid_filter import parse_filter, parse_hs_datetime_format

File ~/haystack/venv/lib/python3.10/site-packages/shaystack/dumper.py:14, in <module>
      9 """
     10 Generic dumper of `Grid`. The mode can be `MODE_ZINC`, `MODE_JSON` or `MODE_CSV`
     11 """
     12 from typing import Any, Optional
---> 14 from .csvdumper import dump_grid as dump_csv_grid, \
...
---> 19 from collections import MutableSequence, Sequence  # pylint: disable=no-name-in-module
     20 from typing import Union, Iterable, Any, Optional, KeysView, Tuple, List, cast, Dict
     22 import pytz

ImportError: cannot import name 'MutableSequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by Amine-OMRI** [comment]
Hello @gr-hayduk @tuscaonline, thanks for the issue report, Shaystack supports python `3.7-3.9` ([click here](https://github.com/engie-group/shaystack/blob/develop/setup.cfg#:~:text=Programming%20Language%20%3A%3A%20Python,Language%20%3A%3A%20Python%20%3A%3A%203.9)), we plan to make the necessary update so that it even supports python `3.10`.

**Comment by Amine-OMRI** [comment]
Hi @tirkarthi, shaystack supports python` 3.10` now so you can try it and if you still have a problem, you could open an issue
