### ISSUE TITLE
pointWrite and hisWrite implementation is missing in db providers (only dumb ping)

### ISSUE THREAD

**Issue by gr-hayduk** [engie-group/shaystack#7]
Hello,

This project allows to load static ontology together with startup data (curVal and history) from files (e.g. .zinc format) into SQL database (I started my journey with sqlite3). So I can start shaystack (REST) API server to query curVal's and hisRead that data.

But now I would also like to use p-h pointWrite and hisWrite methods which are defined in providers/haystack_interface.py only as abstract methods, but are not implemented anywhere else (and NotImplemented exceptions are thrown).

I'd like to start shaystack REST API server to hold ontology and data, then load it with some startup ontology hierarchy and then using shaystack clients (http from external code and from my python code) be able to query the ontology, **update + insert data** and eventually query the current data + history. That's why I need pointWrite and hisWrite. But also I don't see how shaystack' client API can connect to shaystack server (there's no connect method, just read from static files).

Regards!

**Comment by Amine-OMRI** [comment]
Hello, Shaystack **is always in development** and as you were able to see the methods **pointWrite** and **hisWrite** are not yet implemented thus to update the ontology files it is possible to use the method `import_data` which allows to import the file of the source grid to a destination which can be on a bucket s3, a directory or even a mysql db, it will check if the data stored in the grid has changed and will update the data of the ontology according to the provider that was used.
There is also another feature `import_ts` that allows updating only the TimeSeries inside the grid.

For the API connection from the client to the shaystack server, this functionality was not in the project roadmap, other security solutions could handle this like using an API token and an API manager.

kind regards!

**Comment by gr-hayduk** [comment]
Hello,
I assummed that I could write BMS or SCADA driver for shaystack which will update current and historic data in shaystack's db and then an analytical tool will have better source of data+metadata than pure list of tags:values from BMS or SCADA (just like it is for niagara).
I think `import_ts` and `import_data` will be OK for smaller systems with low data rate.

If client and server are not to be communicating, I think it should be clarified in the Readme.md. I am communicating with postman REST API to shaystack server and I expected to use client in place of postman. Now as I understand 'client' is just a module to make it easy to read/parse & write haystack files?

It would also be nice to have more examples of the API. Currently without reading the code, putting breakpoints and debugging what's inside for a given query, there are plenty of cases where errors are misleading or just are silent.

Kind regards!

**Comment by Amine-OMRI** [comment]
The client interface is mostly used to query the Shaystack server, I thought you were talking about authentication.

The client interface can handle several endpoint Api at the same time by pasting the link of the API endpoint(s), which allows to read the ontology and to query the server by filtering by date or by tags and even by asking for a specific version of the ontology.

Inside the repo you will notice that there is 2 project **Shaystack** wich contain the implementation of the grid structure, the diffrent provider and pasreser, and a **Flask app** that will run shaystack and Js UI client that allow to query the shaystack server, so when you run  **Haystack HTTP API** it run the client and the server at the same time

The root /haystack will run the Shaystack server and also the client,[ here is the code that ensures this](https://github.com/engie-group/shaystack/blob/develop/app/blueprint_haystack.py#:~:text=def%20create_haystack_bp(),/haystack%27))

**Comment by FLECOMPTE1965** [comment]
Hello.
We are working on an effective use case and the go-live is planned at the end of july. Some improvments will be released in september. I'll be pleased to discuss with you about your use case and what you'll need in the future.
(frederic.lecompte@engie.com)
At the moment, the ontology files are build with "ETL helpers" but not with write funcitons in the API. We have no effective business case to plan these enhancements.
Kings regards.
